### ISSUE TITLE
floggy esm and jest fail

### ISSUE THREAD

**Issue by boredland** [prisma-labs/konn#34]
#### Description

floggy recently updated to be an esm. I use konn inside a nextjs jest seup. it throwsb:

```
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/jonass/Documents/lala/node_modules/floggy/src/chalk.ts:7
    import chalkPackageSingleton from 'chalk'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I tried workarounds using [transformIgnorePatterns](https://github.com/vercel/next.js/issues/40183#issuecomment-1249077718), but that didn't get me too far:

```
TypeError: Cannot read properties of undefined (reading 'Instance')

      at Object.Instance (node_modules/floggy/src/chalk.ts:9:48)
      at Object.<anonymous> (node_modules/floggy/src/chalk.cts:7:1)
      at Object.<anonymous> (node_modules/floggy/src/filter.cts:1:1)
      at Object.<anonymous> (node_modules/floggy/src/logger.cts:2:1)
      at Object.<anonymous> (node_modules/floggy/src/root-logger.cts:1:1)
      at Object.<anonymous> (node_modules/floggy/src/index.cts:1:1)
      at Object.<anonymous> (node_modules/konn/src/log.ts:1:1)
      at Object.<anonymous> (node_modules/konn/src/runners.ts:4:1)
      at Object.<anonymous> (node_modules/konn/src/provider.ts:3:1)
      at Object.<anonymous> (node_modules/konn/src/Providers/ChildProcess/ChildProcess.ts:3:1)
      at Object.<anonymous> (node_modules/konn/src/indexProviders.ts:2:1)
      at Object.<anonymous> (node_modules/konn/src/index.ts:1:1)
```

Using a resolutions field I pinned the version down to 0.3.1 successfully, but perhaps it would be nicer if konn could pin its dependencies.

**Comment by jasonkuhrt** [comment]
Hm, `floggy` is a hybrid package. Thanks  for raising this!

**Comment by boredland** [comment]
Closing this myself as the reporter — I'm no longer pursuing it, and I'd rather not leave it sitting in your triage queue.

No action is needed from the maintainers, and this says nothing about the validity of the report: if anyone else is hitting the same thing, please reopen or file fresh.

**Comment by boredland** [comment]
Reopening — please disregard my previous comment.

That closure was a mistake on my side: it came from a bulk sweep of my own filed issues, not from a considered decision to withdraw this report. Sorry for the noise in your notifications.

The report stands as originally written.
